"""empty message

Revision ID: 702b5fdd7e5f
Revises: e21cd058f5f8
Create Date: 2023-05-18 17:30:07.580564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702b5fdd7e5f'
down_revision = 'e21cd058f5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color_eyes', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
