"""empty message

Revision ID: 864e8124fb39
Revises: 39f90308457c
Create Date: 2023-05-18 17:41:56.867315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864e8124fb39'
down_revision = '39f90308457c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
